#!/bin/sh

# fnm
curl -fsSL https://fnm.vercel.app/install | bash
if [ -n "$ZSH_VERSION" ]; then
    source $HOME/.zshrc;
elif [ -n "$BASH_VERSION" ]; then
    source $HOME/.bashrc;
fi
fnm install --lts

# npm
npm install -g \
    @bitwarden/cli   \
    alacritty-themes \
    how-2            \
    npm              \
    prettier         \
    wikit            \
    yarn             \
