#!/bin/sh

# fnm
if
	! command -v fnm &
	>/dev/null
then
	curl -fsSL https://fnm.vercel.app/install | bash
	if [ -n "$ZSH_VERSION" ]; then
		source $HOME/.zshrc
	elif [ -n "$BASH_VERSION" ]; then
		source $HOME/.bashrc
	fi
	fnm install --lts
fi

# npm
npm install --force -g \
	@bitwarden/cli \
	alacritty-themes \
	fast-cli \
	how-2 \
	live-server \
	npm \
	prettier \
	wikit \
	write-good \
	yarn
