#!/bin/sh

# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install \
	TheZoraiz/ascii-image-converter/ascii-image-converter \
	gh \
	hugo \
	shfmt \
	topgrade \
	stylua
