#!/bin/sh

# pip install \
pip install --upgrade \
  mycli            \
  pynvim           \
  pytube           \
  ranger-fm        \
  ricksay          \
  speedtest-cli    \
  vimwiki-markdown \
  wisdom-tree      \
