#!/bin/sh
#   __          _                 
#  / _| ___  __| | ___  _ __ __ _ 
# | |_ / _ \/ _` |/ _ \| '__/ _` |
# |  _|  __/ (_| | (_) | | | (_| |
# |_|  \___|\__,_|\___/|_|  \__,_|

read -s -p "Enter Password for sudo: " sudoPW
alias S='echo $sudoPW | sudo -S'

# rpm fusion
S dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# dnf copr
S dnf -y copr enable atim/bottom

# dnf install
S dnf -y install \
    alacritty              \
    bottom                 \
    community-mysql-server \
    conda                  \
    dictd                  \
    direnv                 \
    f33-backgrounds-gnome  \
    ffmpeg                 \
    foliate                \
    fzf                    \
    geary                  \
    gnome-tweaks           \
    googler                \
    highlight              \
    kitty                  \
    ledger                 \
    mpg123                 \
    neofetch               \
    neovim                 \
    pandoc                 \
    poetry                 \
    ripgrep                \
    task                   \
    timew                  \
    tldr                   \
    tmux                   \
    translate-shell        \
    util-linux-user        \
    vlc                    \
    zsh                    \

# flatpak
S flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
S flatpak install -y \
    flathub com.calibre_ebook.calibre     \

# source
source $HOME/myconf/extra-pip
source $HOME/myconf/bootstrap # place after extra-pip
source $HOME/myconf/extra-npm
source $HOME/myconf/zcomp # place after extra-npm
source $HOME/myconf/CHARGE
source $HOME/myconf/dconf

S dnf -y upgrade
S dnf -y autoremove
S dnf -y remove PackageKit-command-not-found

# systemctl
S systemctl start mysqld
S systemctl enable mysqld
