#!/bin/sh

git clone https://github.com/qvieth/myarchive $HOME/MyFolder/myarchive
git clone https://github.com/qvieth/myblog $HOME/MyFolder/myblog
git clone https://github.com/qvieth/mynote $HOME/MyFolder/mynote
