#!/bin/sh
#                         _
#  _ __ ___   __ _ _ __  (_) __ _ _ __ ___
# | '_ ` _ \ / _` | '_ \ | |/ _` | '__/ _ \
# | | | | | | (_| | | | || | (_| | | | (_) |
# |_| |_| |_|\__,_|_| |_|/ |\__,_|_|  \___/
#                      |__/

read -s -p "Enter Password for sudo: " sudoPW
alias S='echo $sudoPW | sudo -S'

# create sudopassword file
echo $sudoPW >$HOME/sudopassword

# full system upgrade
S pacman -Syu --noconfirm

# install
S pacman -S --noconfirm \
	alacritty \
	bottom \
	dictd \
	figlet \
	foliate \
	fzf \
	kitty \
	ledger \
	mariadb \
	neofetch \
	neovim \
	pandoc \
	poetry \
	ripgrep \
	task \
	timew \
	tldr \
	tmux \
	translate-shell \
	vlc \
	w3m \
	yay

# currently missing packages
# googler                \
# conda                  \
# direnv                 \

# mariadb
S mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
S systemctl start mariadb.service
S systemctl enable mariadb.service

# flatpak
S flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
S flatpak install -y \
	flathub com.calibre_ebook.calibre

# source
source $HOME/myconf/extra-pip
source $HOME/myconf/bootstrap # place after extra-pip
source $HOME/myconf/extra-npm
source $HOME/myconf/CHARGE
source $HOME/myconf/dconf

# Manjaro gnome dconf
# themes && icons
dconf write /org/gnome/desktop/interface/gtk-theme "'Matcha-light-sea'"
dconf write /org/gnome/desktop/interface/icon-theme "'Papirus-Light-Maia'"
# background
dconf write /org/gnome/desktop/background/picture-uri "'file:///usr/share/backgrounds/manjaro-gnome/manjarowall17_07.jpg'"
dconf write /org/gnome/desktop/screensaver/picture-uri "'file:///usr/share/backgrounds/manjaro-gnome/manjarowall17_07.jpg'"

# autoremove
S pacman -Rs $(pacman -Qtdq)
